default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
  {% if cookiecutter.versioning == "dynamic" -%}
  - post-commit
  - pre-push
  {%- endif %}

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-case-conflict
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: check-json
        exclude: ^.devcontainer/devcontainer.json
        stages: [pre-commit]
      - id: pretty-format-json
        exclude: ^.devcontainer/devcontainer.json
        args: [--autofix]
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.2"
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.11
    hooks:
      - id: uv-sync
        args: ["--locked"]
        stages:
          - post-checkout
          - post-merge
          - post-rewrite
          {% if cookiecutter.versioning == "dynamic" -%}
          - post-commit
          - pre-push
          {%- endif -%}
